# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: JFrogDocker@1
  inputs:
    command: 'Pull'
    artifactoryConnection: 'jfrogart'
    imageName: 'releases-docker.jfrog.io/jfrog/router:7.135.2'
    skipLogin: false
- task: JFrogDocker@1
  inputs:
    command: 'Scan'
    xrayConnection: 'myjfrogxray'
    imageName: 'releases-docker.jfrog.io/jfrog/router:7.135.2'
    watchesSource: 'none'
    licenses: true
    allowBypassArchiveLimits: false
    threads: '3'
    skipLogin: false
